#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Ivan Shamrai CV
url: '' #'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

analytics: G-LYRZM6MY6G

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development